# Generated by Django 4.0.5 on 2022-06-20 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_remove_recipes_category_recipes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.category'),
        ),
    ]
