# Generated by Django 4.0.5 on 2022-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_review_rate_alter_review_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
