# Generated by Django 4.0.5 on 2022-06-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_uploadedimage_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='img',
            new_name='image',
        ),
    ]
