# Generated by Django 4.0.5 on 2022-06-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_remove_uploadedimage_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', related_query_name='uploaded_image', to='recipes.recipes'),
        ),
    ]
