# Generated by Django 4.0.5 on 2022-06-23 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_uploadedimage_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
