# Generated by Django 4.0.5 on 2022-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_recipes_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='price',
            field=models.CharField(choices=[('33', '$'), ('66', '$$'), ('99', '$$$')], default='33', max_length=3),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='views',
            field=models.IntegerField(),
        ),
    ]
