# Generated by Django 4.0.5 on 2022-06-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_alter_favorites_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
    ]
