# Generated by Django 4.0.5 on 2022-06-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0040_rename_created_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='user',
            new_name='author',
        ),
    ]
