# Generated by Django 4.0.5 on 2022-06-30 05:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0041_rename_user_grocerylist_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceryList',
            new_name='GroceryLists',
        ),
    ]
