# Generated by Django 4.0.5 on 2022-06-22 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipes_rating_test_alter_rating_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
