# Generated by Django 4.0.5 on 2022-06-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_rename_img_uploadedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='user',
        ),
    ]
