# Generated by Django 4.0.5 on 2022-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='price',
            field=models.CharField(choices=[('$', 'Freshman'), ('$$', 'Sophomore'), ('$$$', 'Junior')], default='$', max_length=3),
        ),
    ]
