# Generated by Django 4.0.5 on 2022-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_alter_recipes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='price',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$', max_length=3),
        ),
    ]
