# Generated by Django 4.0.5 on 2022-06-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_rename_ingredients_list_recipes_ingredient_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='caption',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
