# Generated by Django 4.0.5 on 2022-06-30 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_grocerylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
