# Generated by Django 4.0.5 on 2022-06-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_rename_grocerylist_grocerylists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylists',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='grocerylists',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
