# Generated by Django 4.0.5 on 2022-06-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_review_rate'),
        ('users', '0002_customuser_liked_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked_recipes',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_recipes',
            field=models.ManyToManyField(to='recipes.recipes'),
        ),
    ]
